version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: serval-bolt-app${NAME_SUFFIX}
    env_file:
      - .env
    tty: true
    stdin_open: true
    # expose:
    #   - 3000
    # ports:
    #   - "3000:3000"
    init: true
    volumes:
      # バインドマウント
      - ./join_messages.json:/home/node/serval-bolt/join_messages.json
      # 名前付きボリューム
      - serval-bolt-node-modules:/home/node/serval-bolt/node_modules
      - serval-bolt-dist:/home/node/serval-bolt/dist
    networks:
      - app-net
    depends_on:
      - db
  db:
    image: postgres:12.7
    container_name: serval-bolt-db${NAME_SUFFIX}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      # 名前付きボリューム
      - serval-bolt-db-store:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passw0rd
    command: -p ${POSTGRES_PORT}
    networks:
      - app-net
volumes:
  serval-bolt-db-store:
  serval-bolt-node-modules:
  serval-bolt-dist:
networks:
  app-net:
    driver: bridge